In [20]:
import pandas as pd

In [21]:
# Read the file
df = pd.read_csv("Procurement KPI Analysis Dataset.csv")
df

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price,Negotiated_Price,Defective_Units,Compliance
0,PO-00001,Alpha_Inc,2023-10-17,2023-10-25,Office Supplies,Cancelled,1176,20.13,17.81,NaN,Yes
1,PO-00002,Delta_Logistics,2022-04-25,2022-05-05,Office Supplies,Delivered,1509,39.32,37.34,235.0,Yes
2,PO-00003,Gamma_Co,2022-01-26,2022-02-15,MRO,Delivered,910,95.51,92.26,41.0,Yes
3,PO-00004,Beta_Supplies,2022-10-09,2022-10-28,Packaging,Delivered,1344,99.85,95.52,112.0,Yes
4,PO-00005,Delta_Logistics,2022-09-08,2022-09-20,Raw Materials,Delivered,1180,64.07,60.53,171.0,No
...,...,...,...,...,...,...,...,...,...,...,...
772,PO-00773,Delta_Logistics,2023-02-11,2023-02-20,Electronics,Delivered,1685,43.42,42.24,262.0,Yes
773,PO-00774,Alpha_Inc,2022-07-23,NaN,Office Supplies,Delivered,445,68.94,60.35,7.0,Yes
774,PO-00775,Gamma_Co,2022-03-19,2022-04-07,Raw Materials,Delivered,494,94.82,81.89,29.0,Yes
775,PO-00776,Beta_Supplies,2023-08-30,2023-09-11,MRO,Delivered,1306,21.05,18.27,128.0,Yes
776,PO-00777,Beta_Supplies,2023-12-09,2023-12-11,Office Supplies,Delivered,1988,105.20,93.23,187.0,Yes

In [26]:
print(df.isnull().sum())

PO_ID                 0
Supplier              0
Order_Date            0
Delivery_Date        87
Item_Category         0
Order_Status          0
Quantity              0
Unit_Price            0
Negotiated_Price      0
Defective_Units     136
Compliance            0
dtype: int64

In [23]:
print((df == 0).sum())
print(df.describe())

PO_ID               0
Supplier            0
Order_Date          0
Delivery_Date       0
Item_Category       0
Order_Status        0
Quantity            0
Unit_Price          0
Negotiated_Price    0
Defective_Units     4
Compliance          0
dtype: int64
          Quantity  Unit_Price  Negotiated_Price  Defective_Units
count   777.000000  777.000000        777.000000       641.000000
mean   1094.660232   58.283822         53.660721        74.803432
std     647.844551   28.101315         26.094930        69.187870
min      51.000000   10.840000          9.270000         0.000000
25%     615.000000   33.290000         30.460000        26.000000
50%    1075.000000   58.950000         53.800000        49.000000
75%    1548.000000   83.130000         76.550000       100.000000
max    5000.000000  109.170000        107.390000       321.000000

In [30]:
# ดูค่าความเบ้ (skewness) ของทุกคอลัมน์ตัวเลข
df[['Quantity', 'Unit_Price', 'Negotiated_Price', 'Defective_Units']].skew()

Quantity            1.553734
Unit_Price          0.027070
Negotiated_Price    0.071762
Defective_Units     1.380015
dtype: float64

In [56]:
# Defective_Units skew ก่อนหน้า (1.367734) ข้อมูลนี้ เบ้ขวา (outlier เยอะ) ใช้ median ทนต่อ outlier ดีกว่า mean 
#เช่น มีบาง order defect เยอะมาก (เช่น 1000+) จะทำให้ mean สูงผิดจริง
df['Defective_Units'] = df['Defective_Units'].fillna(df['Defective_Units'].median())
df

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price,Negotiated_Price,Defective_Units,Compliance,Lead_Time
0,PO-00001,Alpha_Inc,2023-10-17,2023-10-25,Office Supplies,Cancelled,1176,20.13,17.81,49.0,Yes,8
1,PO-00002,Delta_Logistics,2022-04-25,2022-05-05,Office Supplies,Delivered,1509,39.32,37.34,235.0,Yes,10
2,PO-00003,Gamma_Co,2022-01-26,2022-02-15,MRO,Delivered,910,95.51,92.26,41.0,Yes,20
3,PO-00004,Beta_Supplies,2022-10-09,2022-10-28,Packaging,Delivered,1344,99.85,95.52,112.0,Yes,19
4,PO-00005,Delta_Logistics,2022-09-08,2022-09-20,Raw Materials,Delivered,1180,64.07,60.53,171.0,No,12
...,...,...,...,...,...,...,...,...,...,...,...,...
771,PO-00772,Beta_Supplies,2023-01-20,2023-02-02,Electronics,Delivered,226,102.47,99.16,28.0,Yes,13
772,PO-00773,Delta_Logistics,2023-02-11,2023-02-20,Electronics,Delivered,1685,43.42,42.24,262.0,Yes,9
774,PO-00775,Gamma_Co,2022-03-19,2022-04-07,Raw Materials,Delivered,494,94.82,81.89,29.0,Yes,19
775,PO-00776,Beta_Supplies,2023-08-30,2023-09-11,MRO,Delivered,1306,21.05,18.27,128.0,Yes,12
776,PO-00777,Beta_Supplies,2023-12-09,2023-12-11,Office Supplies,Delivered,1988,105.20,93.23,187.0,Yes,2

In [41]:
df['Delivery_Date'].isna().sum()
print(df['Delivery_Date'].isna().sum())
print(df[['Order_Date','Delivery_Date']].dtypes)

87
Order_Date       datetime64[us]
Delivery_Date    datetime64[us]
dtype: object

In [55]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'])
print(df[['Order_Date','Delivery_Date']].dtypes)

Order_Date       datetime64[us]
Delivery_Date    datetime64[us]
dtype: object

In [50]:
df['Lead_Time'] = (
    df['Delivery_Date'] - df['Order_Date']
).dt.days

(df['Lead_Time'] < 0).sum()

0

In [54]:
df[df['Lead_Time'] < 0]

Empty DataFrame
Columns: [PO_ID, Supplier, Order_Date, Delivery_Date, Item_Category, Order_Status, Quantity, Unit_Price, Negotiated_Price, Defective_Units, Compliance, Lead_Time]
Index: []

In [52]:
df = df[df['Lead_Time'] >= 0] #ลบทิ้ง

In [57]:
# Check for missing values
print("Missing values:\n", df.isnull().sum())

# Check the value to zero
print("\nZero values:\n", (df == 0).sum())

# Duplicate data check
print("\nDuplicate rows:", df.duplicated().sum())

Missing values:
 PO_ID               0
Supplier            0
Order_Date          0
Delivery_Date       0
Item_Category       0
Order_Status        0
Quantity            0
Unit_Price          0
Negotiated_Price    0
Defective_Units     0
Compliance          0
Lead_Time           0
dtype: int64

Zero values:
 PO_ID               0
Supplier            0
Order_Date          0
Delivery_Date       0
Item_Category       0
Order_Status        0
Quantity            0
Unit_Price          0
Negotiated_Price    0
Defective_Units     4
Compliance          0
Lead_Time           0
dtype: int64

Duplicate rows: 0

In [53]:
print(df.describe())
#Show dataset size after cleaning
print("\nDataset shape after cleaning:", df.shape)

                       Order_Date               Delivery_Date     Quantity  \
count                         689                         689   689.000000
mean   2023-01-01 19:22:01.915820  2023-01-12 14:33:36.835994  1100.833091
min           2022-01-01 00:00:00         2022-01-06 00:00:00    51.000000
25%           2022-07-10 00:00:00         2022-07-22 00:00:00   630.000000
50%           2023-01-06 00:00:00         2023-01-21 00:00:00  1094.000000
75%           2023-07-07 00:00:00         2023-07-18 00:00:00  1546.000000
max           2024-01-01 00:00:00         2024-01-12 00:00:00  5000.000000
std                           NaN                         NaN   637.420410

       Unit_Price  Negotiated_Price  Defective_Units   Lead_Time
count  689.000000        689.000000       689.000000  689.000000
mean    58.347068         53.757533        71.394775   10.799710
min     10.840000          9.270000         0.000000    1.000000
25%     33.290000         30.460000        30.000000    6.000000
50%     58.500000         53.370000        49.000000   11.000000
75%     83.420000         77.030000        87.000000   16.000000
max    109.170000        107.390000       321.000000   20.000000
std     28.262833         26.255784        63.657795    5.701688

Dataset shape after cleaning: (689, 12)

In [61]:
df.to_excel("D:/powerbi_dash/fix_cleaned_dataset.xlsx", index=False)